services:
  - type: web
    name: salesforce-metadata-proxy
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn salesforce_api_proxy:app --bind 0.0.0.0:$PORT
    envVars:
      - key: FLASK_ENV
        value: production
      - key: SALESFORCE_API_VERSION
        value: v58.0
